kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-log-analysis-deployment
spec:
  selector:
    matchLabels:
      run: app-log-analysis
  replicas: 2
  template:
    metadata:
      labels:
        run: app-log-analysis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
    spec:
      containers:
        - name: app-log-analysis
          image: $MYCONTAINERREGISGRY/$MYNAMESPACE/app-log-analysis:latest
---
kind: Service
apiVersion: v1
metadata:
  name: app-log-analysis-svc
  labels:
    run: app-log-analysis
spec:
  type: NodePort
  ports:
    - port: 8001
      protocol: TCP
  selector:
    run: app-log-analysis
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-log-analysis-ingress
spec:
  rules:
  - host: $MYINGRESSSUBDOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: app-log-analysis-svc
          servicePort: 8001
